import { useState } from "react";
import { useTimer, type TimerSession } from "../stores/timer";
import { Icon } from "./ui/Icon";

function formatRemaining(ms: number) { const total = Math.ceil(ms / 1000); return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, "0")}`; }
function TimerRow({ session, onPause, onResume, onStop, onPin }: { session: TimerSession; onPause: () => void; onResume: () => void; onStop: () => void; onPin: () => void }) { return <article className={`timer-row ${session.pinned ? "pinned" : ""}`}><button className="timer-row-main" onClick={onPin} aria-label={session.pinned ? `Unpin ${session.label}` : `Pin ${session.label}`}><strong>{session.label}</strong><span>{formatRemaining(session.remainingMs)}{session.paused ? " · Paused" : ""}</span></button><button className="timer-row-action" onClick={session.paused ? onResume : onPause}>{session.paused ? "Resume" : "Pause"}</button><button className="timer-row-action" onClick={onStop} aria-label={`Stop ${session.label}`}>Stop</button></article>; }
export function TimerPanel({ onBack }: { onBack: () => void }) {
  const { sessions, start, pause, resume, stop, pin } = useTimer();
  const [custom, setCustom] = useState("20");
  const [label, setLabel] = useState("");
  return <section className="timer-panel"><header className="panel-header"><button className="back-button" onClick={onBack} aria-label="Back to system controls"><Icon name="back" size="small" /></button><div><h1>Timers</h1><p>{sessions.length ? `${sessions.length} active · tap a timer to pin it` : "Timestamp-based and sleep-safe"}</p></div></header>{sessions.length > 0 && <div className="timer-list">{sessions.map((session) => <TimerRow key={session.id} session={session} onPause={() => pause(session.id)} onResume={() => resume(session.id)} onStop={() => stop(session.id)} onPin={() => pin(session.id)} />)}</div>}<div className="timer-presets">{[5, 20, 60].map((minutes) => <button key={minutes} onClick={() => start(minutes, label || `${minutes}-minute timer`)}><strong>{minutes}</strong><small>minutes</small></button>)}</div><label className="timer-custom">Label<input value={label} placeholder="e.g. laundry" onChange={(event) => setLabel(event.target.value)} /></label><label className="timer-custom">Custom minutes<input type="number" min="1" max="1440" value={custom} onChange={(event) => setCustom(event.target.value)} /><button className="primary-button" onClick={() => start(Number(custom) || 20, label || "Timer")}>Start</button></label></section>;
}
